<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sasidhar" failures="4" tests="4" name="LoginTests" time="26.575" errors="0" timestamp="2025-08-29T23:39:54 IST">
  <testcase classname="com.saucedemo.tests.LoginTest_with_TestNG" name="@AfterMethod tearDown" time="0.001">
    <failure type="org.openqa.selenium.remote.UnreachableBrowserException" message="Error communicating with the remote browser. It may have died.
Build info: version: &amp;apos;4.25.0&amp;apos;, revision: &amp;apos;8a8aea2337&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.6&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [2cbbef476e4e944bf49e3744d309758e, quit []]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 139.0.7258.140, chrome: {chromedriverVersion: 139.0.7258.154 (9e0d6b2b47f..., userDataDir: C:\Users\SASIDHAR\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:46609}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:46609/devtoo..., se:cdpVersion: 139.0.7258.140, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 2cbbef476e4e944bf49e3744d309758e">
      <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [2cbbef476e4e944bf49e3744d309758e, quit []]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 139.0.7258.140, chrome: {chromedriverVersion: 139.0.7258.154 (9e0d6b2b47f..., userDataDir: C:\Users\SASIDHAR\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:46609}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:46609/devtoo..., se:cdpVersion: 139.0.7258.140, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 2cbbef476e4e944bf49e3744d309758e
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:446)
at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:435)
at com.saucedemo.tests.LoginTest_with_TestNG.tearDown(LoginTest_with_TestNG.java:81)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@69100c50 rejected from java.util.concurrent.ThreadPoolExecutor@57ceac3b[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:123)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
... 20 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="com.saucedemo.tests.LoginTest_with_TestNG" name="loginTest" time="23.352">
    <failure type="java.lang.AssertionError" message="Login failed for locked_out_user : secret_sauce | Error: Epic sadface: Username and password do not match any user in this service">
      <![CDATA[java.lang.AssertionError: Login failed for locked_out_user : secret_sauce | Error: Epic sadface: Username and password do not match any user in this service
at com.saucedemo.tests.LoginTest_with_TestNG.loginTest(LoginTest_with_TestNG.java:75)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.saucedemo.tests.LoginTest_with_TestNG" name="loginTest" time="23.543">
    <failure type="java.lang.AssertionError" message="Login failed for standard_user : secret_sauce | Error: Unknown error">
      <![CDATA[java.lang.AssertionError: Login failed for standard_user : secret_sauce | Error: Unknown error
at com.saucedemo.tests.LoginTest_with_TestNG.loginTest(LoginTest_with_TestNG.java:75)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.saucedemo.tests.LoginTest_with_TestNG" name="loginTest" time="23.543">
    <failure type="java.lang.AssertionError" message="Login failed for performance_glitch_user : secret_sauce | Error: Unknown error">
      <![CDATA[java.lang.AssertionError: Login failed for performance_glitch_user : secret_sauce | Error: Unknown error
at com.saucedemo.tests.LoginTest_with_TestNG.loginTest(LoginTest_with_TestNG.java:75)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.saucedemo.tests.LoginTest_with_TestNG" name="loginTest" time="23.543">
    <failure type="java.lang.AssertionError" message="Login failed for problem_user : secret_sauce | Error: Unknown error">
      <![CDATA[java.lang.AssertionError: Login failed for problem_user : secret_sauce | Error: Unknown error
at com.saucedemo.tests.LoginTest_with_TestNG.loginTest(LoginTest_with_TestNG.java:75)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- LoginTests -->
